# Generated by Django 4.0.1 on 2022-01-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crshome', '0002_user_designation_user_station_alter_fir_assignee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_code',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/dp/'),
        ),
    ]
