# Generated by Django 4.0.1 on 2022-01-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crshome', '0004_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='police_id',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
