# Generated by Django 4.0.1 on 2022-01-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crshome', '0005_user_police_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
