# Generated by Django 4.0.1 on 2022-01-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crshome', '0006_feedback_soft_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='video',
        ),
    ]
