# Generated by Django 4.0.1 on 2022-01-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crshome', '0007_remove_complaint_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
